version: '3.8'

services:
  backend:
    build: ./job-board-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

  frontend:
    build: ./job-board-frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobboard
    ports:
      - "5432:5432"
